name: Deploy express-mongo

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use nodejs 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
        
      - name: Using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_FILE }}
          script: |
            whoami
            ls -al
            cd /home/ubuntu/assignment-day7-Ruben
            git pull origin main
            npm install
            npm run app.js